ElasticSearch.Web.ECommerce/Models/ECommercee.cs
namespace ElasticSearch.Web.ECommerce.Models;

public class ECommercee
{
	[JsonPropertyName("_id")] //Nest kütüphanesinde [PropertyName("")] attribütünü kullanıyoruz
	public string Id { get; set; }

	[JsonPropertyName("customer_first_name")]
	public string CustomerFirstName { get; set; }

	[JsonPropertyName("customer_last_name")]
	public string CustomerLastName { get; set; }

	[JsonPropertyName("customer_full_name")]
	public string CustomerFullName { get; set; }

	[JsonPropertyName("customer_gender")]
	public string Gender { get; set; }

	[JsonPropertyName("taxful_total_price")]
	public double TaxFullTotalPrice { get; set; }

	[JsonPropertyName("category")]
	public string[] Category { get; set; }

	[JsonPropertyName("order_id")]
	public int OrderId { get; set; }

	[JsonPropertyName("order_date")]
	public DateTime OrderDate { get; set; }

	[JsonPropertyName("products")]
	public EcommerceProduct[] Products { get; set; }
}

public class EcommerceProduct
{
	[JsonPropertyName("product_id")]
	public long ProductId { get; set; }

	[JsonPropertyName("product_name")]
	public string ProductName { get; set; }
}

ElasticSearch.Web.ECommerce/Models/ErrorViewModel.cs
namespace ElasticSearch.Web.ECommerce.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ElasticSearch.Web.ECommerce/ViewModels/ECommerViewModel.cs
namespace ElasticSearch.Web.ECommerce.ViewModels;

public class ECommerceViewModel
{
    public string Id { get; set; }

    public string CustomerFirstName { get; set; }

    public string CustomerLastName { get; set; }

    public string CustomerFullName { get; set; }

    public string Gender { get; set; }

    public double TaxFullTotalPrice { get; set; }

    public string Category { get; set; }

    public int OrderId { get; set; }

    public string OrderDate { get; set; }
}

ElasticSearch.Web.ECommerce/ViewModels/ECommerceSearchViewModel.cs
namespace ElasticSearch.Web.ECommerce.ViewModels;

public class ECommerceSearchViewModel
{
	[DisplayName("Category")]
	public string Category { get; set; }

	[DisplayName("Gender")]
	public string Gender { get; set; }

	[DisplayName("Order Date (Start)")]
	[DataType(DataType.Date)]
	public DateTime? OrderDateStart { get; set; }

	[DisplayName("Order Date (End)")]
	[DataType(DataType.Date)]
	public DateTime? OrderDateEnd { get; set; }

	[DisplayName("Customer Full Name")]
	public string CustomerFullName { get; set; }
}

ElasticSearch.Web.ECommerce/ViewModels/SearchPageViewModel.cs
namespace ElasticSearch.Web.ECommerce.ViewModels;

public class SearchPageViewModel
{
    public long TotalCount { get; set; }
    public int Page { get; set; } = 1;
    public int PageSize { get; set; } = 10;
    public long PageLinkCount { get; set; }
    public List<ECommerceViewModel> List { get; set; }
    public ECommerceSearchViewModel SearchViewModel { get; set; }

    public string CreatePageUrl(HttpRequest request, long page, int pageSize)
    {
        string currentUrl = new Uri($"{request.Scheme}://{request.Host}{request.Path}{request.QueryString}").AbsoluteUri;

        if (currentUrl.Contains("Page", StringComparison.OrdinalIgnoreCase))
        {
            currentUrl = currentUrl.Replace($"Page={Page}", $"Page={page}", StringComparison.OrdinalIgnoreCase);

            currentUrl = currentUrl.Replace($"PageSize={Page}", $"PageSize={page}", StringComparison.OrdinalIgnoreCase);
        }
        else
        {
            currentUrl = $"{currentUrl}?Page={page}&PageSize={pageSize}";
        }

        return currentUrl;
    }

    public int StartPage()
    {
        return Page - 6 <= 0 ? 1 : Page - 6;
    }

    public long EndPage()
    {
        return Page + 6 >= PageLinkCount ? PageLinkCount : Page + 6;
    }
}

ElasticSearch.Web.ECommerce/Controllers/ECommerceController.cs
namespace ElasticSearch.Web.ECommerce.Controllers;

public class ECommerceController : Controller
	{
		private readonly ECommerceService _eCommerceService;

		public ECommerceController(ECommerceService eCommerceService)
		{
			_eCommerceService = eCommerceService;
		}

		[HttpGet]
		public async Task<IActionResult> Search([FromQuery] SearchPageViewModel searchPageViewModel)
		{
			var (eCommerceList, totalCount, pageLinkCount) = await _eCommerceService.SearchAsync(searchPageViewModel.SearchViewModel, searchPageViewModel.Page, searchPageViewModel.PageSize);

			searchPageViewModel.List = eCommerceList;
			searchPageViewModel.TotalCount = totalCount;
			searchPageViewModel.PageLinkCount = pageLinkCount;

			return View(searchPageViewModel);
		}
	}

ElasticSearch.Web.ECommerce/Views/ECommerce/Search.cshtml
@{
    ViewData["Title"] = "Search";
}
@model SearchPageViewModel
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Search" method="get">
                <div class="mb-3">
                    <label asp-for="SearchViewModel.CustomerFullName" class="form-label"></label>
                    <input asp-for="SearchViewModel.CustomerFullName" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="SearchViewModel.Category" class="form-label"></label>
                    <input asp-for="SearchViewModel.Category" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="SearchViewModel.Gender" class="form-label"></label>
                    <input asp-for="SearchViewModel.Gender" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="SearchViewModel.OrderDateStart" class="form-label"></label>
                    <input asp-for="SearchViewModel.OrderDateStart" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="SearchViewModel.OrderDateEnd" class="form-label"></label>
                    <input asp-for="SearchViewModel.OrderDateEnd" class="form-control">
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>
        </div>
        <div class="col-md-8">
            <div class="alert alert-success">
                <span>Toplam @Model.TotalCount kayıt bulunmuştur.</span>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Customer Full Name</th>
                        <th>Order Date</th>
                        <th>Gender</th>
                        <th>Taxful Total Price</th>
                        <th>Category</th>
                        <th>Order Id</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.List)
                    {
                        <tr>
                            <td>@item.CustomerFullName</td>
                            <td>@item.OrderDate</td>
                            <td>@item.Gender</td>
                            <td>@item.TaxFullTotalPrice</td>
                            <td>@item.Category</td>
                            <td>@item.OrderId</td>
                        </tr>
                    }
                </tbody>
            </table>
            <nav>
                <ul class="pagination">

                    <li class="page-item">
                        <a class="page-link" href="@Model.CreatePageUrl(Context.Request, 1, Model.PageSize)">First</a>
                    </li>

                    @for (int index = Model.StartPage(); index < Model.EndPage(); index++)
                    {
                        <li class="page-item @(Model.Page == index ? "active" : "")">
                            <a class="page-link" href="@Model.CreatePageUrl(Context.Request, index, Model.PageSize)">@index</a>
                        </li>
                    }

                    <li class="page-item">
                        <a class="page-link" href="@Model.CreatePageUrl(Context.Request, Model.PageLinkCount, Model.PageSize)">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

ElasticSearch.Web.ECommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ElasticSearch.Web.ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElasticSearch.Web.ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElasticSearch.Web.ECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ElasticSearch.Web.ECommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ECommerce" asp-action="Search">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ElasticSearch.Web.ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>