ElasticSearch.Web.Blog/Models/Blog.cs
namespace ElasticSearch.Web.Blogs.Models;

public class Blog
{
    [JsonPropertyName("_id")]
    public string Id { get; set; }

    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("content")]
    public string Content { get; set; }

    [JsonPropertyName("tags")]
    public string[] Tags { get; set; }

    [JsonPropertyName("user_id")]
    public Guid UserId { get; set; }

    [JsonPropertyName("created")]
    public DateTime Created { get; set; }
}

ElasticSearch.Web.Blog/Models/BlogViewModel.cs
namespace ElasticSearch.Web.Blogs.Models
{
	public class BlogViewModel
	{
		public string Id { get; set; }
		public string Title { get; set; }
		public string Content { get; set; }
		public string Tags { get; set; }
		public string UserId { get; set; }
		public string Created { get; set; }
	}
}

ElasticSearch.Web.Blog/Models/ErrorViewModel.cs
namespace ElasticSearch.Web.Blogs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElasticSearch.Web.Blog/ViewModels/BlogCreateViewModel.cs
namespace ElasticSearch.Web.Blogs.ViewModels;

public class BlogCreateViewModel
{
    [Required]
    [DisplayName("Blog Title")]
    public string Title { get; set; }

    [Required]
    [DisplayName("Blog Content")]
    public string Content { get; set; }

    [Required]
    [DisplayName("Blog Tags")]
    public string Tags { get; set; }
}

ElasticSearch.Web.Blog/Controllers/BlogController.cs
namespace ElasticSearch.Web.Blogs.Controllers;

public class BlogController : Controller
{
    private readonly BlogService _blogService;

    public BlogController(BlogService blogService)
    {
        _blogService = blogService;
    }

    [HttpGet]
    public IActionResult Save()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Save(BlogCreateViewModel blog)
    {
        bool succedeed = await _blogService.InsertAsync(blog);
        if (!succedeed)
        {
            TempData["result"] = "The blog could not be added.";
            return RedirectToAction(nameof(BlogController.Save));
        }

        TempData["result"] = "The blog has been successfully added.";
        return RedirectToAction(nameof(BlogController.Save));
    }

    [HttpGet]
    public async Task<IActionResult> Search()
    {
		var blogs = await _blogService.SearchAsync(string.Empty);
		return View(blogs);
	}

    [HttpPost]
    public async Task<IActionResult> Search(string searchText)
    {
        ViewBag.SearchText = searchText;

        var blogs = await _blogService.SearchAsync(searchText);
        return View(blogs);
    }
}

ElasticSearch.Web.Blog/Controllers/HomeController.cs
namespace ElasticSearch.Web.Blogs.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ElasticSearch.Web.Blog/Views/Blog/Save.cshtml
@model BlogCreateViewModel
@{
    ViewData["Title"] = "Save";
}


<div class="row">
    <div class="col-md-6 offset-md-3">

        @if (TempData["result"] != null)
        {
            <div class="alert alert-info">
                @TempData["result"]
            </div>
        }

        <h2>Blog Create</h2>

        <form asp-action="Save">

            <div class="mb-3">
                <label asp-for="Title" class="form-label"></label>
                <input asp-for="Title" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Content" class="form-label"></label>
                <textarea asp-for="Content" class="form-control" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <label asp-for="Tags" class="form-label"></label>
                <input asp-for="Tags" class="form-control">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>

        </form>
    </div>
</div>

ElasticSearch.Web.Blog/Views/Blog/Search.cshtml
@{
	ViewData["Title"] = "SearchAsync";
}
@model List<BlogViewModel>

<div class="container">
	<div class="col-md-10 offset-md-1">

		<form asp-action="Search">
			<div class="mb-3">
				<label>SearchAsync(Title,Content)</label>
				<input value="@ViewBag.SearchText" name="searchText" class="form-control" />
			</div>

			<button type="submit">Search</button>
		</form>


		@if (!Model.Any())
		{
			<div class="alert alert-info">sonuç bulunamamıştır.</div>
		}
		else
		{

			<table class="table">

				<thead>
					<tr>
						<th>Id</th>
						<th>Title</th>
						<th>Content</th>
						<th>UserId</th>
						<th>Tags</th>
						<th>Created</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var blog in Model)
					{
						<tr>

							<td>@blog.Id</td>
							<td>@blog.Title</td>
							<td>@blog.Content</td>
							<td>@blog.UserId</td>
							<td>@blog.Tags</td>
							<td>@blog.Created</td>
						</tr>
					}
				</tbody>
			</table>
		}
	</div>
</div>

ElasticSearch.Web.Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElasticSearch.Web.Blogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElasticSearch.Web.Blogs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ElasticSearch.Web.Blogs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Save">Blog Save</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Search">Blog Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ElasticSearch.Web.Blogs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>